site_name: Soroush Personal Blog =))
site_url: https://blog.baboojoo.ir
theme:
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - palette.toggle
  language: en
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Blog:
      - Learning:
          - "FreeBSD": blog/FreeBSD.md
          - "Networking": blog/Networking.md
          - "Programming": blog/Programming.md
          - "Sysadmin Question": blog/Sysadmin_Question.md
          - "Security": blog/security.md
          - "Inventory": blog/inventory.md
          - "Syntax Highlighting in Vim": blog/synatax_hilight_vim.md
          - "Jobs Ad": blog/Jobs-ad.md
          - "Test Cases": blog/test_cases.md
          - "QA Testing": blog/QA-Testing.md
          - "QA-ST": blog/QA-ST.md
          - "NO": blog/NO.md
          - "ParSy": blog/ParSy.md
          - "OS": blog/OS.md
          - "Network Security": blog/Network_security.md
          - "Sysadmin HPC Learning": blog/sysadmin-HPC-learning.md
          - "Note": blog/note.md
          - "Sccout NC": blog/sccuot_NC.md
          - "04.06.2024": blog/04.06.2024.md
          - "04.06.2024 Backup": blog/04.06.2024-bck.md
          - "05.01.25": blog/05.01.25.md
          - "06.01.25": blog/06.01.25.md

plugins:
  - blog
  - search
  # - rss:
  #     match_path: blog/posts/.*
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags
  #     image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
  # - tags:
  #     enabled: true
  #     tags_file: tags.md

extra:
  social:
    - icon: material/github
      link: https://github.com/Soroush9978

copyright: Copyright © 2025 Soroush
repo_url: https://github.com/Soroush9978/blog

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex

